runtime: python27
api_version: 1
threadsafe: true
service: website-python

handlers:
- url: /sushigo/sushigo_main_page.htm
  static_files: sushigo/sushigo_main_page.htm
  upload: sushigo/sushigo_main_page.htm

- url: /sushigo/sushigo.js
  static_files: sushigo/sushigo.js
  upload: sushigo/sushigo.js

- url: /sushigo/sushigo_response.js
  static_files: sushigo/sushigo_response.js
  upload: sushigo/sushigo_response.js

- url: /sushigo/images/(.*)$
  static_files: sushigo/images/\1
  upload: sushigo/images/.*
  application_readable: true

- url: /sushigo/sushigo_server
  script: sushigo.sushigo_server.app